doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Users:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Users/Infrastructure/Database/ORM'
                prefix: 'App\Users\Domain\Entity'
                alias: App
            Refresh:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Domain/Entity/Token'
                prefix: 'App\Shared\Domain\Entity\Token'
                alias: Refresh
            Lots:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Lots/Infrastructure/Database/ORM'
                prefix: 'App\Lots\Domain\Entity'
                alias: Lots
            Buyers:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Buyers/Infrastructure/Database/ORM'
                prefix: 'App\Buyers\Domain\Entity'
                alias: Buyers
            Orders:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Orders/Infrastructure/Database/ORM'
                prefix: 'App\Orders\Domain\Entity'
                alias: Orders

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
