security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Users\Domain\Entity\User
                property: email
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                username_path: email
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /api/auth/token/refresh

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/social-login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/current, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/lot/create, roles: [ROLE_VENDOR, ROLE_ADMIN] }
        - { path: ^/api/lot/delete, roles: [ROLE_VENDOR, ROLE_ADMIN] }
        - { path: ^/api/lot/update, roles: [ROLE_VENDOR, ROLE_ADMIN] }
        - { path: ^/api/lot/list, roles: PUBLIC_ACCESS }
        - { path: ^/api/buyer/set, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/buyer/delete, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/buyer/list, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/buyer/current, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/lot/edit/price, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/api/order/set, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/order/delete, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/order/list, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/order/\d+$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/order/pay, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext
