version: "3.3"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  database:
    container_name: database
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
